---
# tasks file for ansible-role-win-teams
- name: Set registy key for WVD environment
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Teams
    name: IsWVDEnvironment
    data: 1
    type: dword
  when: teams_is_wvd_environment

- name: Set 32-bit registy key for WVD environment
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\WOW6432Node\Microsoft\Teams
    name: IsWVDEnvironment
    data: 1
    type: dword
  when:
    - teams_is_wvd_environment
    - teams_is_32bit

- name: Install vc_redist
  ansible.windows.win_package:
    path: '{{ teams_vc_redist_download_url }}'
    product_id: '{{ teams_vc_redist_product_id }}'
    state: present
    arguments: '/passive /norestart'
    validate_certs: '{{ validate_certs | default(omit) }}'
    proxy_password: '{{ proxy_password | default(omit) }}'
    proxy_url : '{{ proxy_url  | default(omit) }}'
    proxy_use_default_credential: '{{ use_default_credential | default(omit) }}'
    proxy_username: '{{ proxy_username | default(omit) }}'
  when: teams_is_wvd_environment

- name: Install WebRTC
  ansible.windows.win_package:
    path: '{{ teams_web_rtc_download_url }}'
    state: present
    validate_certs: '{{ validate_certs | default(omit) }}'
    proxy_password: '{{ proxy_password | default(omit) }}'
    proxy_url : '{{ proxy_url  | default(omit) }}'
    proxy_use_default_credential: '{{ use_default_credential | default(omit) }}'
    proxy_username: '{{ proxy_username | default(omit) }}'
  when: teams_is_wvd_environment

- name: Install Teams x64
  ansible.windows.win_package:
    path: '{{ teams_x64_download_url }}'
    state: present
    arguments: '{{ (teams_installer_arguments_autostart + " " + teams_installer_arguments) | trim }}'
    validate_certs: '{{ validate_certs | default(omit) }}'
    proxy_password: '{{ proxy_password | default(omit) }}'
    proxy_url : '{{ proxy_url  | default(omit) }}'
    proxy_use_default_credential: '{{ use_default_credential | default(omit) }}'
    proxy_username: '{{ proxy_username | default(omit) }}'
  when: teams_is_32bit == false

- name: Install Teams x86
  ansible.windows.win_package:
    path: '{{ teams_x86_download_url }}'
    state: present
    arguments: '{{ (teams_installer_arguments_autostart + " " + teams_installer_arguments) | trim }}'
    validate_certs: '{{ validate_certs | default(omit) }}'
    proxy_password: '{{ proxy_password | default(omit) }}'
    proxy_url : '{{ proxy_url  | default(omit) }}'
    proxy_use_default_credential: '{{ use_default_credential | default(omit) }}'
    proxy_username: '{{ proxy_username | default(omit) }}'
  when: teams_is_32bit

- name: Remove HKLM Autorun x64
  ansible.windows.win_regedit:
    path: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run"
    name: "Teams"
    state: absent
  when: teams_remove_hklm_autorun

- name: Remove HKLM Autorun x86
  ansible.windows.win_regedit:
    path: "HKLM:\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Run"
    name: "Teams"
    state: absent
  when:
    - teams_remove_hklm_autorun

- name: Register Microsoft.Teams.AddinLoader
  ansible.builtin.import_tasks: register-addinloader.yml
  when:
    - teams_per_machine_install
    - teams_register_addinloader
